-- 在 MySQL 数据库中创建 pets 表
CREATE TABLE IF NOT EXISTS pets (
  id INT AUTO_INCREMENT PRIMARY KEY,
  name VARCHAR(255) NOT NULL,
  species VARCHAR(50) NOT NULL,
  category VARCHAR(50) DEFAULT 'food',
  age INT NOT NULL,
  description VARCHAR(500) DEFAULT '',
  image_url VARCHAR(500) DEFAULT '',
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);
